# Generated by Django 2.2 on 2021-06-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('OIDC_RP_CLIENT_ID', models.TextField()),
                ('OIDC_RP_CLIENT_SECRET', models.TextField()),
                ('OIDC_OP_AUTHORIZATION_ENDPOINT', models.TextField()),
                ('OIDC_OP_TOKEN_ENDPOINT', models.TextField()),
                ('OIDC_OP_USER_ENDPOINT', models.TextField()),
                ('OIDC_AUTH_REQUEST_EXTRA_PARAMS', models.TextField(blank=True, null=True)),
                ('OIDC_RP_SIGN_ALGO', models.TextField(blank=True, null=True)),
                ('OIDC_RP_IDP_SIGN_KEY', models.TextField(blank=True, null=True)),
                ('OIDC_OP_JWKS_ENDPOINT', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
