# Generated by Django 2.2 on 2021-06-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozilla_django_oidc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcconfig',
            name='OIDC_CREATE_USER',
            field=models.BooleanField(default=False),
        ),
    ]
