# Generated by Django 2.2 on 2021-06-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozilla_django_oidc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcconfig',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
